name : test
    
on:
    push:
        branches: [ actions_1 ]
    
jobs:
    build:
        runs-on: self-hosted
        steps:
        # - uses: actions/checkout@v2
            - name: Checkout PowerShell
              run: $PSVersionTable
          